/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:028975ec-9a4a-4683-b228-4c78828afaaf",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_mUko7LBC5",
    "aws_user_pools_web_client_id": "2db0lpu887pdihgp8emsaaitq",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://4r2hov6k6vctzoxwyrirzxpv4i.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qwv4ahumfbdl5kgzfxmmek4mtm"
};


export default awsmobile;
